server:
  port: ${server.register.port1}
  
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.register.port1}/eureka/,http://${eureka.instance.hostname}:${server.register.port2}/eureka/,http://${eureka.instance.hostname}:${server.register.port3}/eureka/